FROM ubi8/ubi:8.3 

MAINTAINER Franklin A Abraham <franklinab90@gmail.com>

ENV PORT 8080 

RUN yum install -y httpd && yum clean all 

RUN sed -ri -e "/^Listen 80/c\Listen 8080" /etc/httpd/conf/httpd.conf && \
    chown -R 48:48 /etc/httpd/logs/ && \
    chown -R 48:48 /run/httpd/

USER 48 

# Expose the custom port that you provided in the ENV var
EXPOSE 8080
# Copy all files under src/ folder to Apache DocumentRoot (/var/www/html) 
COPY src/ /var/www/html/
# Start Apache in the foreground
CMD ["httpd", "-D", "FOREGROUND"]
